### ISSUE TITLE
Unable to download Vanilla_UI_Plus_Fallout_3_948 

### ISSUE THREAD

**Issue by Dustinds3000** [zpok3/Waters-of-Life#1]
(Wabbajack.Installer.StandardInstaller) Unable to download Vanilla_UI_Plus_Fallout_3_948 mirror bc i cant get this to work from moddb.7z (HTTPDownloader+State|https://github.com/zpok3/Waters-of-Life/releases/download/v.1.0/Vanilla_UI_Plus_Fallout_3_948.mirror.bc.i.cant.get.this.to.work.from.moddb.7z)
00:00:07.299 [FATAL] (Wabbajack.Installer.StandardInstaller) Cannot continue, was unable to download one or more archives

**Comment by zpok3** [comment]
I'll fix this as soon as I can, should just be a matter of renaming VUI+ to have dots instead of spaces and recompiling the Wabbajack.

**Comment by zpok3** [comment]
should be fixed now
